### ISSUE TITLE
Error running instance-segmentation-security inference via OpenCV's dnn (with IE)

### ISSUE THREAD

**Issue by orgicus** [openvinotoolkit/open_model_zoo#2799]
Hi,

I'm running into an error inferring instance-segmentation-security-1039 using OpenVino via OpenCV's dnn module:
`cv2.error: [ PARAMETER_MISMATCH ] Failed to set output Blob. Dimensions mismatch.

This my basic test:
```python
import cv2 as cv
import numpy as np
model_name = 'instance-segmentation-security-1039'
net = cv.dnn.readNetFromModelOptimizer(model_name+'.xml', model_name+'.bin')
print(net.dump())
cap = cv.VideoCapture("test_video.mp4")
# instance-seg = 480
(n, c, h, w) = (1, 3, 480, 480)
# yolact = 550
# (n, c, h, w) = (1, 3, 550, 550)

while cv.waitKey(1) < 0:
    hasFrame, frame = cap.read()
    
    if not hasFrame:
        break
    
    blob = cv.dnn.blobFromImage(cv.resize(frame, (w, h)))
    net.setInput(blob)
    out = net.forward()

    cv.imshow('OpenVINO', frame)
```
This is using OpenCV 4.5.3-openvino (which shipped with openvino_2021.4.689).

I can run the instance_segmentation_demo using the IE directly just fine.

Is it possible to run the same demo via OpenCV ? 
If so, how ?

Thank you so much for your time,
George

**Comment by vladimir-dudnik** [comment]
@allnes @alvoron could you please comment on this?

**Comment by alalek** [comment]
> PARAMETER_MISMATCH

relates https://github.com/opencv/opencv/pull/20410

This patch will be released with OpenVINO 2022.1 (2021.4.x LTS updates are out of scope for now)

Also you can build OpenCV from source code with enabled InferenceEngine: https://github.com/opencv/opencv/wiki/Intel%27s-Deep-Learning-Inference-Engine-backend#build-opencv-from-source

**Comment by orgicus** [comment]
Hi Alex,

I'll try to to build OpenCV from source with InferenceEngine enabled.

This may take some time: I'll report back with findings.

In the meantime, I thought that using the OpenCV version that ships with OpenVINO should work.
I double checked and indeed cv::getBuildInfo() shows that (as expected) is has been built from source with InferenceEngine:

```
General configuration for OpenCV 4.5.3-openvino =====================================
  Version control:               8cfe9546f3c3314ac5b5287f9542153d28f66bb6

  Platform:
    Timestamp:                   2021-09-08T02:22:19Z
    Host:                        Windows 10.0.19043 AMD64
    CMake:                       3.14.5
    CMake generator:             Visual Studio 16 2019
    CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/MSBuild/Current/Bin/MSBuild.exe
    MSVC:                        1926
    Configuration:               Debug Release

  CPU/HW features:
    Baseline:                    SSE SSE2 SSE3 SSSE3 SSE4_1 POPCNT SSE4_2
      requested:                 SSE4_2
    Dispatched code generation:  FP16 AVX AVX2 AVX512_SKX
      requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
      FP16 (1 files):            + FP16 AVX
      AVX (5 files):             + AVX
      AVX2 (31 files):           + FP16 FMA3 AVX AVX2
      AVX512_SKX (7 files):      + FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX

  C/C++:
    Built as dynamic libs?:      YES
    C++ standard:                11
    C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe  (ver 19.26.28806.0)
    C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise         /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /GS /sdl /guard:cf /w34018 /w34146 /w34244 /w34267 /w34302 /w34308 /w34509 /w34532 /w34533 /w34700 /w34789 /w34995 /w34996 /MP  /MD /O2 /Ob2 /DNDEBUG
    C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise         /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /GS /sdl /guard:cf /w34018 /w34146 /w34244 /w34267 /w34302 /w34308 /w34509 /w34532 /w34533 /w34700 /w34789 /w34995 /w34996 /MP  /MDd /Zi /Ob0 /Od /RTC1
    C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
    C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise         /GS /sdl /guard:cf /w34018 /w34146 /w34244 /w34267 /w34302 /w34308 /w34509 /w34532 /w34533 /w34700 /w34789 /w34995 /w34996 /MP   /MD /O2 /Ob2 /DNDEBUG
    C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise         /GS /sdl /guard:cf /w34018 /w34146 /w34244 /w34267 /w34302 /w34308 /w34509 /w34532 /w34533 /w34700 /w34789 /w34995 /w34996 /MP /MDd /Zi /Ob0 /Od /RTC1
    Linker flags (Release):      /machine:x64   /guard:cf /dynamicbase /INCREMENTAL:NO
    Linker flags (Debug):        /machine:x64   /guard:cf /dynamicbase /debug /INCREMENTAL
    ccache:                      NO
    Precompiled headers:         NO
    Extra dependencies:
    3rdparty dependencies:

  OpenCV modules:
    To be built:                 calib3d core dnn features2d flann gapi highgui imgcodecs imgproc ml objdetect photo python3 stitching ts video videoio
    Disabled:                    world
    Disabled by dependency:      -
    Unavailable:                 java python2
    Applications:                tests perf_tests apps
    Documentation:               NO
    Non-free algorithms:         NO

  Windows RT support:            NO

  GUI:
    Win32 UI:                    YES

  Media I/O:
    ZLib:                        build (ver 1.2.11)
    JPEG:                        build-libjpeg-turbo (ver 2.1.0-62)
    PNG:                         build (ver 1.6.37)
    HDR:                         YES
    SUNRASTER:                   YES
    PXM:                         YES
    PFM:                         YES

  Video I/O:
    FFMPEG:                      YES (prebuilt binaries)
      avcodec:                   YES (58.134.100)
      avformat:                  YES (58.76.100)
      avutil:                    YES (56.70.100)
      swscale:                   YES (5.9.100)
      avresample:                YES (4.0.0)
    DirectShow:                  YES
    Media Foundation:            YES
      DXVA:                      YES
    Intel Media SDK:             YES (S:/msdk/win-2018R2/lib/x64/libmfx_vs2015.lib)

  Parallel framework:            Concurrency

  Trace:                         YES (with Intel ITT)

  Other third-party libraries:
    Intel IPP:                   2020.0.0 Gold [2020.0.0]
           at:                   C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/build_release/3rdparty/ippicv/ippicv_win/icv
    Intel IPP IW:                sources (2020.0.0)
              at:                C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/build_release/3rdparty/ippicv/ippicv_win/iw
    Inference Engine:            YES (2021040000 / 2021.4.0)
        * libs:                  C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/inference_engine/lib/intel64/Release/inference_engine.lib / C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/inference_engine/lib/intel64/Debug/inference_engined.lib C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/inference_engine/bin/intel64/Release/inference_engine.dll / C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/inference_engine/bin/intel64/Debug/inference_engined.dll C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/inference_engine/bin/intel64/Release/inference_engine.dll C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/inference_engine/bin/intel64/Debug/inference_engined.dll
        * includes:              C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/inference_engine/include
    nGraph:                      YES (0.0.0+cd81789)
        * libs:                  C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/ngraph/lib/ngraph.lib / C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/ngraph/lib/ngraphd.lib C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/ngraph/lib/ngraph.dll / C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/ngraph/lib/ngraphd.dll C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/ngraph/lib/ngraph.dll C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/ngraph/lib/ngraphd.dll
        * includes:              C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/deployment_tools/ngraph/include
    Custom HAL:                  NO
    Protobuf:                    build (3.5.1)

  OpenCL:                        YES (NVD3D11)
    Include path:                C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/opencv/3rdparty/include/opencl/1.2
    Link libraries:              Dynamic load

  Python 3:
    Interpreter:                 C:/miniconda/envs/py3_env/python.exe (ver 3.4.5)
    Libraries:                   C:/miniconda/envs/py3_env/libs/python34.lib (ver 3.4.5)
    numpy:                       C:/miniconda/envs/py3_env/lib/site-packages/numpy/core/include (ver 1.11.3)
    install path:                python/python3/cv2/python-3

  Python (for build):            C:/miniconda/envs/py3_env/python.exe

  Install to:                    C:/jenkins/workspace/OpenCV/OpenVINO/2021.4/build/windows/build_release/install
-----------------------------------------------------------------
``` 

I notice the Jenkins build isn't using the exact OpenVINO version (2021040000 / 2021.4.0 and not  2021.4.689), but
I do hope as long as it's 2021.4 I hope it should work. What do you think ?

(I am confused because I thought using the OpenCV version that ships with OpenVINO will be simpelst/safest way to use OpenVINO from OpenCV)

Thank you so much for supporting,
George

**Comment by vladimir-dudnik** [comment]
@orgicus your expectations are correct in general. OpenCV DNN with OpenVINO backend should support the same models which supported through direct OpenVINO API. But the reality is that OpenCV DNN might miss some features, and OpenCV team (and community) working on fixes, when issues detected.

**Comment by orgicus** [comment]
@vladimir-dudnik Ok, if I understood correctly OpenCV DNN with OpenVINO backend as it ships might be lagging just a bit behind what the the direct OpenVINO API can do already (e.g. older models might work ok, but newer models relying on newer OpenVINO feature might not). 

🤞 building OpenCV from source with OpenVINO will do the trick (e.g. latest OpenCV + latest OpenVINO)

Thank you for the clarifications: much appreciated.

**Comment by orgicus** [comment]
@vladimir-dudnik Apologies for the long delayed. Finally made time to try this again.

I've pulled the latest version of OpenCV (4.5.4-dev) and tried to build with openvino_2021.4.689.
This are the CMake flags and config output:

```cmake
 D:\gp\cv\opencv\build_openvino>cmake -DWITH_INF_ENGINE=ON -DENABLE_CXX11=ON -DWITH_NGRAPH=ON ..
-- 'Release' build type is used by default. Use CMAKE_BUILD_TYPE to specify build type (Release or Debug)
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.17763.
-- Detected processor: AMD64
-- Performing Test HAVE_CXX_W15240
-- Performing Test HAVE_CXX_W15240 - Success
-- Performing Test HAVE_C_W15240
-- Performing Test HAVE_C_W15240 - Success
-- libjpeg-turbo: VERSION = 2.1.0, BUILD = opencv-4.5.4-dev-libjpeg-turbo
-- Could NOT find OpenJPEG (minimal suitable version: 2.0, recommended version >= 2.3.1). OpenJPEG will be built from sources
-- OpenJPEG: VERSION = 2.4.0, BUILD = opencv-4.5.4-dev-openjp2-2.4.0
-- OpenJPEG libraries will be built from sources: libopenjp2 (version "2.4.0")
-- found Intel IPP (ICV version): 2020.0.0 [2020.0.0 Gold]
-- at: D:/gp/cv/opencv/build_openvino/3rdparty/ippicv/ippicv_win/icv
-- found Intel IPP Integration Wrappers sources: 2020.0.0
-- at: D:/gp/cv/opencv/build_openvino/3rdparty/ippicv/ippicv_win/iw
-- Could not find OpenBLAS include. Turning OpenBLAS_FOUND off
-- Could not find OpenBLAS lib. Turning OpenBLAS_FOUND off
-- Could NOT find BLAS (missing: BLAS_LIBRARIES)
-- Could NOT find LAPACK (missing: LAPACK_LIBRARIES)
    Reason given by package: LAPACK could not be found because dependency BLAS could not be found.

-- Detected InferenceEngine: cmake package (2021.4.1)
-- InferenceEngine: 2021.4.1
-- Detected ngraph: cmake package (0.0.0+14e67d8)
-- VTK is not found. Please set -DVTK_DIR in CMake to VTK build directory, or to VTK install subdirectory with VTKConfig.cmake file
-- FFMPEG: Download: opencv_videoio_ffmpeg.dll
-- FFMPEG: Download: opencv_videoio_ffmpeg_64.dll
-- FFMPEG: Download: ffmpeg_version.cmake
-- Module opencv_alphamat disabled because the following dependencies are not found: Eigen
-- Caffe:   NO
-- Protobuf:   NO
-- Glog:   NO
-- freetype2:   NO
-- harfbuzz:    NO
-- Julia not found. Not compiling Julia Bindings.
CMake Warning (dev) at D:/gp/cv/opencv_contrib/modules/matlab/cmake/init.cmake:24 (set):
  Cannot set "DOXYGEN_BLACKLIST": current scope has no parent.
Call Stack (most recent call first):
  cmake/OpenCVModule.cmake:298 (include)
  cmake/OpenCVModule.cmake:364 (_add_modules_1)
  cmake/OpenCVModule.cmake:385 (ocv_glob_modules)
  CMakeLists.txt:919 (ocv_register_modules)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Module opencv_ovis disabled because OGRE3D was not found
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find gflags - Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Failed to find gflags - Could not find gflags include directory, set GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
-- Failed to find glog - Could not find glog include directory, set GLOG_INCLUDE_DIR to directory containing glog/logging.h
-- Module opencv_sfm disabled because the following dependencies are not found: Eigen Glog/Gflags
-- Tesseract:   NO
-- Allocator metrics storage type: 'long long'
-- Registering hook 'INIT_MODULE_SOURCES_opencv_dnn': D:/gp/cv/opencv/modules/dnn/cmake/hooks/INIT_MODULE_SOURCES_opencv_dnn.cmake
-- DNN: Enabling Inference Engine nGraph API support
-- opencv_dnn: filter out cuda4dnn source code
-- Excluding from source files list: <BUILD>/modules/dnn/layers/layers_common.rvv.cpp
-- highgui: using builtin backend: WIN32UI
-- rgbd: CERES support is disabled. Ceres Solver is Required for Posegraph optimization
--
-- General configuration for OpenCV 4.5.4-dev =====================================
--   Version control:               4.5.4-92-g17234f82d0-dirty
--
--   Extra modules:
--     Location (extra):            D:/gp/cv/opencv_contrib/modules
--     Version control (extra):     4.5.1-60-g4e85f8c6
--
--   Platform:
--     Timestamp:                   2021-11-02T22:18:51Z
--     Host:                        Windows 10.0.17763 AMD64
--     CMake:                       3.21.3
--     CMake generator:             Visual Studio 16 2019
--     CMake build tool:            C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/MSBuild/Current/Bin/MSBuild.exe
--     MSVC:                        1929
--     Configuration:               Debug Release
--
--   CPU/HW features:
--     Baseline:                    SSE SSE2 SSE3
--       requested:                 SSE3
--     Dispatched code generation:  SSE4_1 SSE4_2 FP16 AVX AVX2 AVX512_SKX
--       requested:                 SSE4_1 SSE4_2 AVX FP16 AVX2 AVX512_SKX
--       SSE4_1 (15 files):         + SSSE3 SSE4_1
--       SSE4_2 (1 files):          + SSSE3 SSE4_1 POPCNT SSE4_2
--       FP16 (0 files):            + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 AVX
--       AVX (4 files):             + SSSE3 SSE4_1 POPCNT SSE4_2 AVX
--       AVX2 (30 files):           + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2
--       AVX512_SKX (5 files):      + SSSE3 SSE4_1 POPCNT SSE4_2 FP16 FMA3 AVX AVX2 AVX_512F AVX512_COMMON AVX512_SKX
--
--   C/C++:
--     Built as dynamic libs?:      YES
--     C++ standard:                11
--     C++ Compiler:                C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe  (ver 19.29.30136.0)
--     C++ flags (Release):         /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MD /O2 /Ob2 /DNDEBUG
--     C++ flags (Debug):           /DWIN32 /D_WINDOWS /W4 /GR  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /EHa /wd4127 /wd4251 /wd4324 /wd4275 /wd4512 /wd4589 /MP  /MDd /Zi /Ob0 /Od /RTC1
--     C Compiler:                  C:/Program Files (x86)/Microsoft Visual Studio/2019/Professional/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
--     C flags (Release):           /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP   /MD /O2 /Ob2 /DNDEBUG
--     C flags (Debug):             /DWIN32 /D_WINDOWS /W3  /D _CRT_SECURE_NO_DEPRECATE /D _CRT_NONSTDC_NO_DEPRECATE /D _SCL_SECURE_NO_WARNINGS /Gy /bigobj /Oi  /fp:precise     /MP /MDd /Zi /Ob0 /Od /RTC1
--     Linker flags (Release):      /machine:x64  /INCREMENTAL:NO
--     Linker flags (Debug):        /machine:x64  /debug /INCREMENTAL
--     ccache:                      NO
--     Precompiled headers:         YES
--     Extra dependencies:
--     3rdparty dependencies:
--
--   OpenCV modules:
--     To be built:                 aruco bgsegm bioinspired calib3d ccalib core datasets dnn dnn_objdetect dnn_superres dpm face features2d flann fuzzy gapi hfs highgui img_hash imgcodecs imgproc intensity_transform line_descriptor mcc ml objdetect optflow phase_unwrapping photo plot quality rapid reg rgbd saliency shape stereo stitching structured_light superres surface_matching tracking ts video videoio videostab xfeatures2d ximgproc xobjdetect xphoto
--     Disabled:                    java_bindings_generator js_bindings_generator python_bindings_generator python_tests text wechat_qrcode world
--     Disabled by dependency:      -
--     Unavailable:                 alphamat cnn_3dobj cudaarithm cudabgsegm cudacodec cudafeatures2d cudafilters cudaimgproc cudalegacy cudaobjdetect cudaoptflow cudastereo cudawarping cudev cvv freetype hdf java julia matlab ovis python2 python3 sfm viz
--     Applications:                apps
--     Documentation:               NO
--     Non-free algorithms:         NO
--
--   Windows RT support:            NO
--
--   GUI:                           WIN32UI
--     Win32 UI:                    YES
--     VTK support:                 NO
--
--   Media I/O:
--     ZLib:                        build (ver 1.2.11)
--     JPEG:                        build-libjpeg-turbo (ver 2.1.0-62)
--     WEBP:                        build (ver encoder: 0x020f)
--     PNG:                         build (ver 1.6.37)
--     TIFF:                        build (ver 42 - 4.2.0)
--     JPEG 2000:                   build (ver 2.4.0)
--     OpenEXR:                     build (ver 2.3.0)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
--
--   Video I/O:
--     DC1394:                      NO
--     FFMPEG:                      YES (prebuilt binaries)
--       avcodec:                   YES (58.134.100)
--       avformat:                  YES (58.76.100)
--       avutil:                    YES (56.70.100)
--       swscale:                   YES (5.9.100)
--       avresample:                YES (4.0.0)
--     GStreamer:                   NO
--     DirectShow:                  YES
--     Media Foundation:            YES
--       DXVA:                      YES
--
--   Parallel framework:            Concurrency
--
--   Trace:                         YES (with Intel ITT)
--
--   Other third-party libraries:
--     Intel IPP:                   2020.0.0 Gold [2020.0.0]
--            at:                   D:/gp/cv/opencv/build_openvino/3rdparty/ippicv/ippicv_win/icv
--     Intel IPP IW:                sources (2020.0.0)
--               at:                D:/gp/cv/opencv/build_openvino/3rdparty/ippicv/ippicv_win/iw
--     Lapack:                      NO
--     Inference Engine:            YES (2021020000 / 2021.4.1)
--         * libs:                  D:/gp/cv/openvino/openvino_2021/deployment_tools/inference_engine/lib/intel64/Release/inference_engine.lib / D:/gp/cv/openvino/openvino_2021/deployment_tools/inference_engine/lib/intel64/Debug/inference_engined.lib D:/gp/cv/openvino/openvino_2021/deployment_tools/inference_engine/bin/intel64/Release/inference_engine.dll / D:/gp/cv/openvino/openvino_2021/deployment_tools/inference_engine/bin/intel64/Debug/inference_engined.dll D:/gp/cv/openvino/openvino_2021/deployment_tools/inference_engine/bin/intel64/Release/inference_engine.dll D:/gp/cv/openvino/openvino_2021/deployment_tools/inference_engine/bin/intel64/Debug/inference_engined.dll
--         * includes:              D:/gp/cv/openvino/openvino_2021/deployment_tools/inference_engine/include
--     nGraph:                      YES (0.0.0+14e67d8)
--         * libs:                  D:/gp/cv/openvino/openvino_2021/deployment_tools/ngraph/lib/ngraph.lib / D:/gp/cv/openvino/openvino_2021/deployment_tools/ngraph/lib/ngraphd.lib D:/gp/cv/openvino/openvino_2021/deployment_tools/ngraph/lib/ngraph.dll / D:/gp/cv/openvino/openvino_2021/deployment_tools/ngraph/lib/ngraphd.dll D:/gp/cv/openvino/openvino_2021/deployment_tools/ngraph/lib/ngraph.dll D:/gp/cv/openvino/openvino_2021/deployment_tools/ngraph/lib/ngraphd.dll
--         * includes:              D:/gp/cv/openvino/openvino_2021/deployment_tools/ngraph/include
--     Eigen:                       NO
--     Custom HAL:                  NO
--     Protobuf:                    build (3.5.1)
--
--   OpenCL:                        YES (NVD3D11)
--     Include path:                D:/gp/cv/opencv/3rdparty/include/opencl/1.2
--     Link libraries:              Dynamic load
--
--   Python (for build):            C:/Users/d3/AppData/Local/Programs/Python/Python39/python.exe
--
--   Install to:                    D:/gp/cv/opencv/build_openvino/install
-- -----------------------------------------------------------------
```

Sadly I've got stuck with a few n_graph related opencv_dnn compiler error:
```
D:\gp\cv\opencv\modules\dnn\src\layers\normalize_bbox_layer.cpp(354,57): error C2039: 'Multiply': is not a member of 'n
graph::op::v0' [D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
D:\gp\cv\openvino\openvino_2021\deployment_tools\ngraph\include\ngraph/op/xor.hpp(48): message : see declaration of 'ng
raph::op::v0' [D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
D:\gp\cv\opencv\modules\dnn\src\layers\normalize_bbox_layer.cpp(354,1): error C2065: 'Multiply': undeclared identifier
[D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
D:\gp\cv\opencv\modules\dnn\src\layers\normalize_bbox_layer.cpp(354,29): error C2672: 'std::make_shared': no matching o
verloaded function found [D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
D:\gp\cv\opencv\modules\dnn\src\layers\normalize_bbox_layer.cpp(354,1): error C2974: 'std::make_shared': invalid templa
te argument for '_Ty', type expected [D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\include\memory(2747): messag
e : see declaration of 'std::make_shared' [D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
D:\gp\cv\opencv\modules\dnn\src\layers\normalize_bbox_layer.cpp(356,1): error C3536: 'mul': cannot be used before it is
 initialized [D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
D:\gp\cv\opencv\modules\dnn\src\layers\normalize_bbox_layer.cpp(356,1): error C2664: 'cv::dnn::InfEngineNgraphNode::Inf
EngineNgraphNode(std::shared_ptr<ngraph::Node> &&)': cannot convert argument 1 from 'int' to 'std::shared_ptr<ngraph::N
ode> &&' [D:\gp\cv\opencv\build_openvino\modules\dnn\opencv_dnn.vcxproj]
```

I expected, as advised the latest version of (OpenCV (4.5.4-dev) and openvino_2021.4.689 to work.
Is there a specific OpenCV/OpenVINO version pair I should be using instead ? If so, what do you recommend ?
Otherwise any minor tweaks/patches you recommend I manually apply to get the build going (and hopefully run openvino inference from OpenCV) ?

Thank you so much,
George

**Comment by alalek** [comment]
4.5.4-dev should work with OpenVINO 2021.4.689 package (2021.4.1 release)

> Inference Engine:            YES (2021020000 / 2021.4.1)
> 2021020000 / 2021.4.1

We have here unaligned declared and used IE versions (OpenCV uses OpenVINO product version). Current value says that we using OpenVINO 2021.2.0 which is not correct.
We need to replace: 2021020000 => 2021040100 (`INF_ENGINE_RELEASE` CMake variable) to properly build code (e.g., compile [this code](https://github.com/opencv/opencv/blob/4.5.4/modules/dnn/src/layers/normalize_bbox_layer.cpp#L351-L355) at least).

Perhaps this value is stored in CMakeCache.txt somewhere from previous old cmake runs.
There is general CMake rule that we need to drop its caches if we change/upgrade dependencies. So, to avoid other issues it is better to build from the clean build directory.

**Comment by orgicus** [comment]
Hi @alalek ,

Many thanks for the suggestion. 
Sorry, I totally forgot I had multiple versions of OpenVINO and the cache variable `INF_ENGINE_RELEASE` CMake variable remained out of date. I've cleaned the previous OpenVINO install and it worked like a charm ! 👏 

I can confirm this fixed the issue and I can run a c++ example using OpenVINO via OpenCV.

(Slightly off topic, if you could point in the right direction regarding OpenCV OpenVINO documentation I would be greatful. I'm interested in how I could easily get input and output layer names and shapes to convert to the right formats. With OpenVINO directly it's straight forward, I didn't quite get how to do the same with OpenCV)
